# Generated by Django 3.2.8 on 2021-10-15 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1000)),
                ("image_path", models.CharField(max_length=255, unique=True)),
                (
                    "updated_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
