# Generated by Django 3.2.8 on 2021-10-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="image_path",
        ),
    ]
