# Generated by Django 3.2.8 on 2021-10-15 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_remove_posts_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="image_path",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
